### ISSUE TITLE
V2.0.0 plan todo

### ISSUE THREAD

**Issue by xland** [xland/ScreenCapture#36]
- [x]  Switch Blend2d render engine to skia
- [x]  Allow modify all history elements by mouse
- [x]  Small toolbar
- [x]  Start draw element when mouse click (number)
- [x]  Finish most enhancements in the issue list
- [x]  Support CMake build system
- [x]  Tool Button tool tip
- [x]  Pin window with out tool bar by default
- [x]  Draw multi line text one time
- [ ]  Multi language support
- [ ]  Application configurable
- [ ]  Support for mac

**Comment by Alvazz** [comment]
老板，能说说为什么从 Blend2d 换到 Skia 吗？

**Comment by xland** [comment]
@Alvazz 

可以，
1、Blend2D提供的能力有点弱，API略少（不举例子了）。
2、Blend2D只有软渲染，未来发展会受到限制。
3、Blend2D作者用爱发电维护项目，更新不够及时，很多作者自己想做的事拖了好几年还没做完。
（这一点Skia也有问题，Skia是更新太快，导致很多API不兼容的问题）
4、Skia更受欢迎，Chrome,Android背后都是它，搞好它，对这个产品以及产品的参与者都有好处。

以上。

**Comment by Alvazz** [comment]
了解，我深入研究过Blend2D这个项目，怎么说呢，我个人觉得作者当初的设计思路还是挺好的，可能后期精力没跟上吧，确实导致好几个比较重大的遗留bug都没修复。

**Comment by Alvazz** [comment]
额外还有个问题请教下，虽然使用了Skia，但是似乎没从代码里发现采用 GPU 加速吗？

**Comment by Alvazz** [comment]
明白，所以使用下来，你觉得Skia的CPU绘制性能如何？

**Comment by xland** [comment]
自己测吧^_^

**Comment by wuqi** [comment]
有没有试过腾讯开源的那个tgfx呢,那个据说比skia快,也轻一些,看接口skia的大部分接口是有的,不太确定是否缺啥接口

**Comment by xland** [comment]
@wuqi
看上去是个很不错的项目，
但我不会轻易尝试，我有我的担忧（担心对该项目产生不良影响，不便公开发表）
